import { Restaurant } from "./types";

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: "z1",
    name: "Behrouz Biryani",
    cuisine: "Biryani",
    rating: 4.5,
    deliveryTime: 35,
    price: 349,
    platform: "zomato",
    offer: "20% off up to ₹80",
  },
  {
    id: "s1",
    name: "Behrouz Biryani",
    cuisine: "Biryani",
    rating: 4.4,
    deliveryTime: 30,
    price: 349,
    platform: "swiggy",
    offer: "Free delivery",
  },
  {
    id: "z2",
    name: "Barbeque Nation",
    cuisine: "BBQ & Grill",
    rating: 4.3,
    deliveryTime: 45,
    price: 599,
    platform: "zomato",
  },
  {
    id: "s2",
    name: "Burger King",
    cuisine: "Burgers",
    rating: 4.1,
    deliveryTime: 20,
    price: 249,
    platform: "swiggy",
    offer: "Buy 1 Get 1",
  },
  {
    id: "z3",
    name: "Amul Ice Cream",
    cuisine: "Desserts",
    rating: 4.2,
    deliveryTime: 22,
    price: 149,
    platform: "zomato",
  },
  {
    id: "s3",
    name: "Naturals Ice Cream",
    cuisine: "Desserts",
    rating: 4.6,
    deliveryTime: 18,
    price: 179,
    platform: "swiggy",
    offer: "10% off",
  },
];
